import type { TeamMember } from "../types";

export const teamMembers: TeamMember[] = [
	// Organizers (Leadership)
	{
		id: "organizer-1",
		name: "Toprak Uçkun",
		title: "Organizer",
		role: "leader",
		team: "leadership",
		photoUrl: "/team/toprak.png",
		socialLinks: [
			{ platform: "linkedin", url: "https://www.linkedin.com/in/toprak-uckun/" },
		],
	},
	{
		id: "organizer-2",
		name: "Göktuğ Yücel",
		title: "Co-Organizer",
		role: "leader",
		team: "leadership",
		photoUrl: "/team/goktug.png",
		socialLinks: [
			{ platform: "linkedin", url: "https://www.linkedin.com/in/goktug-yucel-28b823296/" },
		],
	},

	// Organizasyon Takımı
	{
		id: "org-leader",
		name: "Sirac Ketenoğlu",
		title: "Organization Team Leader",
		role: "team-leader",
		team: "organization",
		photoUrl: "/team/sirac.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/siracketenoglu/" }],
	},
	{
		id: "org-1",
		name: "Ezgi Öz",
		title: "Organization Team",
		role: "member",
		team: "organization",
		photoUrl: "/team/ezgi-oz.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/ezgi-oz-mis/" }],
	},
	{
		id: "org-2",
		name: "Rüstem Avcı",
		title: "Organization Team",
		role: "member",
		team: "organization",
		photoUrl: "/team/rustem.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/r%C3%BCstem-avc%C4%B1/" }],
	},
	{
		id: "org-3",
		name: "Irmak Dindar",
		title: "Organization Team",
		role: "member",
		team: "organization",
		photoUrl: "/team/irmak.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/irmak-dindar-10b4a4286/" }],
	},
	{
		id: "org-4",
		name: "Özgür Korkmaz",
		title: "Organization Team",
		role: "member",
		team: "organization",
		photoUrl: "/team/ozgur.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/aozgurkorkmaz/" }],
	},
	{
		id: "org-5",
		name: "Nisanas Turan",
		title: "Organization Team",
		role: "member",
		team: "organization",
		photoUrl: "/team/nisanas.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/nisanas-turan-863b85351/" }],
	},
	{
		id: "org-6",
		name: "Ezgi Aynal",
		title: "Organization Team",
		role: "member",
		team: "organization",
		photoUrl: "/team/ezgi-aynal.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/ezgi-aynal-7b022a2a3/" }],
	},
	{
		id: "org-7",
		name: "Berna Başıhoş",
		title: "Organization Team",
		role: "member",
		team: "organization",
		photoUrl: "/team/berna.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/selinay-berna-ba%C5%9F%C4%B1ho%C5%9F-b5960a26b/" }],
	},

	// Reklam ve Tanıtım Takımı
	{
		id: "marketing-leader",
		name: "Selin Erol",
		title: "Marketing Team Leader",
		role: "team-leader",
		team: "marketing",
		photoUrl: "/team/selin.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/zehra-selin-erol-4094a5330/" }],
	},
	{
		id: "marketing-1",
		name: "Cansın Mat",
		title: "Marketing Team",
		role: "member",
		team: "marketing",
		photoUrl: "/team/cansin.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/cans%C4%B1n-mat-96b607362/" }],
	},
	{
		id: "marketing-2",
		name: "Yağmur Bayram",
		title: "Marketing Team",
		role: "member",
		team: "marketing",
		photoUrl: "/team/yagmur-bayram.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/ya%C4%9Fmur-bayram/" }],
	},
	{
		id: "marketing-3",
		name: "Elif Altın",
		title: "Marketing Team",
		role: "member",
		team: "marketing",
		photoUrl: "/team/elif.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/elif-alt%C4%B1n-326a76376/" }],
	},
	{
		id: "marketing-4",
		name: "Sultan Esen Murat",
		title: "Marketing Team",
		role: "member",
		team: "marketing",
		photoUrl: "/team/sultan.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/esen-murat/" }],
	},
	{
		id: "marketing-5",
		name: "Yağmur Korucu",
		title: "Marketing Team",
		role: "member",
		team: "marketing",
		photoUrl: "/team/yagmur-korucu.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/ya%C4%9Fmur-korucu-494902389/" }],
	},

	// Sponsorluk Takımı
	{
		id: "sponsorship-leader",
		name: "Safi Eren Şimşek",
		title: "Sponsorship Team Leader",
		role: "team-leader",
		team: "sponsorship",
		photoUrl: "/team/safi.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/safi-eren-%C5%9Fim%C5%9Fek-74a016330/" }],
	},
	{
		id: "sponsorship-1",
		name: "Emre Aköz",
		title: "Sponsorship Team",
		role: "member",
		team: "sponsorship",
		photoUrl: "/team/emre-akoz.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/emre-ak%C3%B6z-9621ab222/" }],
	},
	{
		id: "sponsorship-2",
		name: "Melis Babacan",
		title: "Sponsorship Team",
		role: "member",
		team: "sponsorship",
		photoUrl: "/team/melis.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/melisbabacan/" }],
	},
	{
		id: "sponsorship-3",
		name: "Yusuf Bilal Tanısa",
		title: "Sponsorship Team",
		role: "member",
		team: "sponsorship",
		photoUrl: "/team/yusuf.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/yusuf-bilal-tan%C4%B1sa-41122829b/" }],
	},
	{
		id: "sponsorship-4",
		name: "İlayda Gürbüzerol",
		title: "Sponsorship Team",
		role: "member",
		team: "sponsorship",
		photoUrl: "/team/ilayda.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/ilayda-g%C3%BCrb%C3%BCzerol-552841269/" }],
	},
	{
		id: "sponsorship-5",
		name: "Sude Erdoğan",
		title: "Sponsorship Team",
		role: "member",
		team: "sponsorship",
		photoUrl: "/team/sude-erdogan.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/sude-erdo%C4%9Fan-441201311/" }],
	},
	{
		id: "sponsorship-6",
		name: "Ela Naz Acar",
		title: "Sponsorship Team",
		role: "member",
		team: "sponsorship",
		photoUrl: "/team/ela.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/ela-naz-acar-386629350/" }],
	},
	{
		id: "sponsorship-7",
		name: "Emirhan Sezgin",
		title: "Sponsorship Team",
		role: "member",
		team: "sponsorship",
		photoUrl: "/team/emirhan-sezgin.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/emirhan-sezgin-078476388/" }],
	},

	// Yazılım Takımı
	{
		id: "software-leader",
		name: "Berat Ölmez",
		title: "Software Team Leader",
		role: "team-leader",
		team: "software",
		photoUrl: "/team/berat.png",
		socialLinks: [{ platform: "linkedin", url: "https://tr.linkedin.com/in/seberatolmez" }],
	},
	{
		id: "software-1",
		name: "Emirhan Kotan",
		title: "Software Team",
		role: "member",
		team: "software",
		photoUrl: "/team/emirhan-kotan.png",
		socialLinks: [{ platform: "linkedin", url: "https://tr.linkedin.com/in/emirhan-kotan-ba3842379" }],
	},
	{
		id: "software-2",
		name: "Doğukan Ürker",
		title: "Software Team",
		role: "member",
		team: "software",
		photoUrl: "/team/dogukan.png",
		socialLinks: [{ platform: "linkedin", url: "https://tr.linkedin.com/in/dogukanurker" }],
	},
	{
		id: "software-3",
		name: "Sude Tuncu",
		title: "Software Team",
		role: "member",
		team: "software",
		photoUrl: "/team/sude-tuncu.png",
		socialLinks: [{ platform: "linkedin", url: "https://tr.linkedin.com/in/sude-tuncu" }],
	},
	{
		id: "software-4",
		name: "Murat Muzaffer",
		title: "Software Team",
		role: "member",
		team: "software",
		photoUrl: "/team/murat.png",
		socialLinks: [{ platform: "linkedin", url: "https://tr.linkedin.com/in/murat-muzaffer" }],
	},
	{
		id: "software-5",
		name: "Burak Kaya",
		title: "Software Team",
		role: "member",
		team: "software",
		photoUrl: "/team/burak-kaya.jpg",
		socialLinks: [{ platform: "linkedin", url: "https://tr.linkedin.com/in/burak-kaya-984b09380" }],
	},
];

