import type { TeamMember } from "../types";

export const teamMembers: TeamMember[] = [
	// Organizers (Leadership)
	{
		id: "organizer-1",
		name: "Toprak Uçkun",
		title: "Organizer",
		role: "leader",
		team: "leadership",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/organizers/toprak_uckun.png",
		socialLinks: [
			{ platform: "linkedin", url: "https://www.linkedin.com/in/toprak-uckun/" },
		],
	},
	{
		id: "organizer-2",
		name: "Göktuğ Yücel",
		title: "Co-Organizer",
		role: "leader",
		team: "leadership",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/organizers/goktug_yucel.png",
		socialLinks: [
			{ platform: "linkedin", url: "https://www.linkedin.com/in/goktug-yucel-28b823296/" },
		],
	},

	// Organizasyon Takımı
	{
		id: "org-leader",
		name: "Sirac Ketenoğlu",
		title: "Organization Team Leader",
		role: "team-leader",
		team: "organization",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/organization_team/sirac_ketenoglu.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/siracketenoglu/" }],
	},
	{
		id: "org-1",
		name: "Ezgi Öz",
		title: "Organization Team",
		role: "member",
		team: "organization",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/organization_team/ezgi_oz.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/ezgi-oz-mis/" }],
	},
	{
		id: "org-2",
		name: "Rüstem Avcı",
		title: "Organization Team",
		role: "member",
		team: "organization",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/organization_team/rustem_avci.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/r%C3%BCstem-avc%C4%B1/" }],
	},
	{
		id: "org-3",
		name: "Ahmet Özgür",
		title: "Organization Team",
		role: "member",
		team: "organization",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/organization_team/ahmet_ozgur_korkmaz.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/aozgurkorkmaz/" }],
	},
	{
		id: "org-4",
		name: "Nisanas Turan",
		title: "Organization Team",
		role: "member",
		team: "organization",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/organization_team/nisanas_turan.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/nisanas-turan-863b85351/" }],
	},
	{
		id: "org-5",
		name: "Ezgi Aynal",
		title: "Organization Team",
		role: "member",
		team: "organization",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/organization_team/ezgi_aynal.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/ezgi-aynal-7b022a2a3/" }],
	},
	{
		id: "org-6",
		name: "Berna Başıhoş",
		title: "Organization Team",
		role: "member",
		team: "organization",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/organization_team/selinay_berna_basihos.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/selinay-berna-ba%C5%9F%C4%B1ho%C5%9F-b5960a26b/" }],
	},

	// Reklam ve Tanıtım Takımı
	{
		id: "marketing-leader",
		name: "Cansın Mat",
		title: "Marketing Team Leader",
		role: "team-leader",
		team: "marketing",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/marketing_team/cansin_mat.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/cans%C4%B1n-mat-96b607362/" }],
	},
	{
		id: "marketing-1",
		name: "Yağmur Sabırlı",
		title: "Marketing Team",
		role: "member",
		team: "marketing",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/marketing_team/Yagmur_sabirli.jpeg",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/yagmur-sabirli/" }],
	},
	{
		id: "marketing-2",
		name: "Elif Altın",
		title: "Marketing Team",
		role: "member",
		team: "marketing",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/marketing_team/elif_altin.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/elif-alt%C4%B1n-326a76376/" }],
	},
	{
		id: "marketing-3",
		name: "Sultan Esen Murat",
		title: "Marketing Team",
		role: "member",
		team: "marketing",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/marketing_team/sultan_esen_murat.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/esen-murat/" }],
	},
	{
		id: "marketing-4",
		name: "Yağmur Korucu",
		title: "Marketing Team",
		role: "member",
		team: "marketing",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/marketing_team/yagmur_korucu.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/ya%C4%9Fmur-korucu-494902389/" }],
	},

	// Sponsorluk Takımı
	{
		id: "sponsorship-leader",
		name: "Selin Erol",
		title: "Sponsorship Team Leader",
		role: "team-leader",
		team: "sponsorship",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/sponsorship_team/selin_erol.jpeg",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/zehra-selin-erol-4094a5330/" }],
	},
	{
		id: "sponsorship-1",
		name: "Sude Erdoğan",
		title: "Sponsorship Team",
		role: "member",
		team: "sponsorship",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/sponsorship_team/sude_erdogan.jpeg",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/sude-erdo%C4%9Fan-441201311/" }],
	},
	{
		id: "sponsorship-2",
		name: "Emirhan Sezgin",
		title: "Sponsorship Team",
		role: "member",
		team: "sponsorship",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/sponsorship_team/emirhan_sezgin.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/emirhan-sezgin-078476388/" }],
	},
	{
		id: "sponsorship-3",
		name: "Irmak Dindar",
		title: "Sponsorship Team",
		role: "member",
		team: "sponsorship",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/sponsorship_team/%C4%B1rmak_dindar.png",
		socialLinks: [{ platform: "linkedin", url: "https://www.linkedin.com/in/irmak-dindar-10b4a4286/" }],
	},

	// Yazılım Takımı
	{
		id: "software-leader",
		name: "Berat Ölmez",
		title: "Software Team Leader",
		role: "team-leader",
		team: "software",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/software_team/berat_olmez.png",
		socialLinks: [{ platform: "linkedin", url: "https://tr.linkedin.com/in/seberatolmez" }],
	},
	{
		id: "software-1",
		name: "Emirhan Kotan",
		title: "Software Team",
		role: "member",
		team: "software",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/software_team/emirhan_kotan.png",
		socialLinks: [{ platform: "linkedin", url: "https://tr.linkedin.com/in/emirhan-kotan-ba3842379" }],
	},
	{
		id: "software-2",
		name: "Doğukan Ürker",
		title: "Software Team",
		role: "member",
		team: "software",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/software_team/dogukan_urker.png",
		socialLinks: [{ platform: "linkedin", url: "https://tr.linkedin.com/in/dogukanurker" }],
	},
	{
		id: "software-3",
		name: "Sude Tuncu",
		title: "Software Team",
		role: "member",
		team: "software",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/software_team/sude_tuncu.png",
		socialLinks: [{ platform: "linkedin", url: "https://tr.linkedin.com/in/sude-tuncu" }],
	},
	{
		id: "software-4",
		name: "Murat Muzaffer",
		title: "Software Team",
		role: "member",
		team: "software",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/software_team/murat_muzaffer.png",
		socialLinks: [{ platform: "linkedin", url: "https://tr.linkedin.com/in/murat-muzaffer" }],
	},
	{
		id: "software-5",
		name: "Burak Kaya",
		title: "Software Team",
		role: "member",
		team: "software",
		photoUrl: "https://raw.githubusercontent.com/GDG-Yasar-Software-Team/mail-assets/main/team/software_team/burak_kaya.jpg",
		socialLinks: [{ platform: "linkedin", url: "https://tr.linkedin.com/in/burak-kaya-984b09380" }],
	},
];

